version: '3.3'
services:
  api:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ./backend
    image: webpersonal.azurecr.io/jb-api:latest
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      - NODE_ENV=development
      - SERVER_PORT=8080
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=jb_ci
      - MYSQL_PASSWORD=jb_ci
      - MYSQL_DATABASE=jb_ci
      - RESTRICTED_LOGINS=false
  frontend:
    build:
      context: ./frontend
    image: webpersonal.azurecr.io/jb-frontend:latest
    ports:
      - "8081:80"
    expose:
      - 8081
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=jb_ci
      - MYSQL_PASSWORD=jb_ci
      - MYSQL_DATABASE=jb_ci
  test:
    build:
      dockerfile: Dockerfile.test
      context: ./backend
