name: CI
on: [push]

jobs:
  test:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Server
        run: docker compose build db api test
      - name: Run Tests
        run: docker compose run test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install
        working-directory: ./backend
        run: yarn install --frozen-lockfile
      - name: Run linting
        working-directory: ./backend
        run: yarn run lint
      - name: Run prettier
        working-directory: ./backend
        run: yarn run format
